Add an option for the Visvalingam simplification algorithm
felt/tippecanoe pull request #16
Opened 2022-09-29 22:36 UTC by e-n-f

2022-09-29 23:00 UTC, migurski requested changes
Looks good! I put two suggestions in comments, otherwise good to go and I am thrilled that we can benefit from @paulmach’s work

2022-09-29 23:13 UTC, e-n-f commented on geometry.cpp
> +	return out;
oops, yes!

2022-09-29 23:14 UTC, e-n-f commented on version.hpp
> +#define VERSION "v2.6.5"
Good point!

2022-09-29 23:35 UTC, e-n-f commented on geometry.cpp
> +			double sim = simplification * (0.1596 * z + 0.878);
The second adjustment is from this set of experiments with existing `--simplification` values and the resulting output size for `ne_10m_admin_0_countries` at z0, compared to sqrt(visvalingam area * zoom adjustment) that yields approximately the same output size:

existing -S | output size | visvalingam area | output size | sqrt(area * zoomscale) | output size
----------- | ----------- | --------------- | ----------- | --------------------
--- | ------
0.5 | 3527690 | 1000000 | 3085053 | 0.9 | 3085049
1 | 2168684 | 2000000 | 2225159 | 1.4 | 2225155
2 | 1544182 | 6000000 | 1557178 | 2.4 | 1557174
4 | 1231908 | 16000000 | 1285993 | 4.6 | 1230857
8 | 1084641 | 80000000 | 1086389 | 9.3 | 1078328
16 | 1016324 | 300000000 | 1016803 | 17.5 | 1015243
32 | 973557 | 2000000000 | 973644 | 44 | 973589
64 | 961327 | 15900000000 | 960927 | 123 | 960919

```
gnuplot> stats "log" using (log($1)):(log($9))
  Linear Model:       y = 1.002 x + 0.3043
```

The first adjustment then comes from doing the same at multiple zoom levels to see what Visvalingam `-S` with the previous adjustment yields about the same output size as a constant Douglas-Peucker `-S`:

zoom level | existing -S | visvalingam -S
---------- | ---------- | ----------
5 | 4 | 7
4 | 4 | 6
3 | 4 | 5.2
2 | 4 | 4.55
1 | 4 | 4.1
0 | 4 | 3.8

```
gnuplot> stats "vis-scaling" using 1:($5 / $3)
  Linear Model:       y = 0.1596 x + 0.878
```

I am not exactly thrilled with this process but can't think of a cleaner way to relate the threshold parameters for the two algorithms.

2022-09-29 23:37 UTC, e-n-f commented on geometry.cpp
> +			double sim = simplification * (0.1596 * z + 0.878);
Looking at this again now, I clearly messed up on reproducing the `-S 0.5` size.

2022-09-30 09:32 UTC, bdon commented
Nice! Is this more time-consuming than Douglas-Peucker?

2022-09-30 18:59 UTC, e-n-f commented
@bdon Yes, Douglas-Peucker is faster.

2022-09-30 19:00 UTC, merged